package net.vo;
// Generated 22 mars 2014 10:04:24 by Hibernate Tools 3.6.0



/**
 * Creancier generated by hbm2java
 */
public class Creancier  implements java.io.Serializable {


     private Integer id;
     private String denomination;
     private String formeJuridique;
     private String nomContact;
     private String registreDeCommerce;
     private String identifiantFiscal;
     private String cnss;
     private String tel;
     private String fax;
     private String email;

    public Creancier() {
    }

	
    public Creancier(String denomination, String formeJuridique) {
        this.denomination = denomination;
        this.formeJuridique = formeJuridique;
    }
    public Creancier(String denomination, String formeJuridique, String nomContact, String registreDeCommerce, String identifiantFiscal, String cnss, String tel, String fax, String email) {
       this.denomination = denomination;
       this.formeJuridique = formeJuridique;
       this.nomContact = nomContact;
       this.registreDeCommerce = registreDeCommerce;
       this.identifiantFiscal = identifiantFiscal;
       this.cnss = cnss;
       this.tel = tel;
       this.fax = fax;
       this.email = email;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getDenomination() {
        return this.denomination;
    }
    
    public void setDenomination(String denomination) {
        this.denomination = denomination;
    }
    public String getFormeJuridique() {
        return this.formeJuridique;
    }
    
    public void setFormeJuridique(String formeJuridique) {
        this.formeJuridique = formeJuridique;
    }
    public String getNomContact() {
        return this.nomContact;
    }
    
    public void setNomContact(String nomContact) {
        this.nomContact = nomContact;
    }
    public String getRegistreDeCommerce() {
        return this.registreDeCommerce;
    }
    
    public void setRegistreDeCommerce(String registreDeCommerce) {
        this.registreDeCommerce = registreDeCommerce;
    }
    public String getIdentifiantFiscal() {
        return this.identifiantFiscal;
    }
    
    public void setIdentifiantFiscal(String identifiantFiscal) {
        this.identifiantFiscal = identifiantFiscal;
    }
    public String getCnss() {
        return this.cnss;
    }
    
    public void setCnss(String cnss) {
        this.cnss = cnss;
    }
    public String getTel() {
        return this.tel;
    }
    
    public void setTel(String tel) {
        this.tel = tel;
    }
    public String getFax() {
        return this.fax;
    }
    
    public void setFax(String fax) {
        this.fax = fax;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

}


